services:
  svc1:
    image: ghcr.io/umputun/echo-http
    hostname: svc1
    container_name: svc1
    command: --message="hello world from svc1"
    labels:
      proxy.http.host: "svc1.local"
      proxy.http.port: "8080"
    networks:
      - proxy-network

  svc2:
    image: ghcr.io/umputun/echo-http
    hostname: svc2
    container_name: svc2
    command: --message="hello world from svc2"
    labels:
      proxy.http.host: "svc2.local"
      proxy.http.port: "8080"
    networks:
      - proxy-network

networks:
  proxy-network:
    name: ${PROXY_NETWORK:-proxy-network}
    external: true