services:
  proxy:
    image: ghcr.io/moontechs/proxy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LOG_LEVEL: "DEBUG"
      LOG_CALLER: "false"
      DOCKER_HOST: "unix:///var/run/docker.sock"
      PROXY_NETWORK: "${PROXY_NETWORK:-proxy-network}"
    networks:
      - proxy-network

networks:
  proxy-network:
    name: ${PROXY_NETWORK:-proxy-network}
    external: true
